' not implemented / standardized yet

@startuml business-partner-relationship

skinparam dpi 50

package "Business Partner Relationship and References" {
  entity BusinessPartner {
    ExternalID
    ...
  }

  entity BusinessPartnerRelationship {
    ExternalID
    CreatedAt
    UpdatedAt
  }

  class BusinessPartnerRelationshipState {
    ValidFrom
    ValidTo
  }

  enum BusinessPartnerRelationshipStateType {
    Active
    Inactive
  }

  enum BusinessPartnerRelationshipReason {
    ReplacedDueToAcquisition
    ReplacedDueToMerger
    ReplacedDueToSpinOff
    ReplacedDueToDivestiture
    ReplacedDueToCarveOut
    ReplacedDueToPrivatization
    ReplacedDueToInitialPublicOffering
    ReplacedDueToWrongData
    ...
  }

  enum BusinessPartnerRelationshipType {
    IsAlternativeHeadquarterFor
    IsReplacedBy
    IsManagedBy
    ...
  }

  BusinessPartnerRelationship "*" -l-> "1" BusinessPartner : Target
  BusinessPartnerRelationship "*" -l-> "1" BusinessPartner : Source
  BusinessPartnerRelationship "*" -d-o "1" BusinessPartnerRelationshipType : Type
  BusinessPartnerRelationship "*" -d-o "0..1" BusinessPartnerRelationshipReason : Reason

  BusinessPartnerRelationship "1" *-d-> "*" BusinessPartnerRelationshipState : States
  BusinessPartnerRelationshipState "*" -d-o "1" BusinessPartnerRelationshipStateType : Type
}

hide methods
hide BusinessPartnerRelationship methods
@enduml