@startuml changelog-entry

skinparam dpi 50

package "Changelog Entry and References" {
  entity BusinessPartner {
    External ID
    ...
  }
  
  entity ChangelogEntry {
    Timestamp
  }

  enum ChangelogType {
    CREATE
    UPDATE
  }

  ChangelogEntry "*" -u-> "1" BusinessPartner : ExternalID

  ChangelogEntry "*" -d-o "1" ChangelogType : ChangelogType
}

hide methods
@enduml