@startuml identifier-mapping-entry

skinparam dpi 50

package "Identifier Mapping Entry and References" {
  abstract class BusinessPartner {}
  
  entity IdentifierMappingEntry {
    IdentifierValue
  }

  IdentifierMappingEntry "*" .u.> "1" BusinessPartner : BPN
}

hide methods
hide BusinessPartner members
@enduml