import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  sidebar_standards: [{type: 'autogenerated', dirName: 'standards'}],
  sidebar_op_model: [{type: 'autogenerated', dirName: 'operating-model'}],
  sidebar_certification: [{type: 'autogenerated', dirName: 'certification'}],
  sidebar_regulatory_framework: [{type: 'autogenerated', dirName: 'regulatory-framework'}],
  sidebar_working_model: [{type: 'autogenerated', dirName: 'working-model'}],
  sidebar_architecture_guardrails: [{type: 'autogenerated', dirName: 'architecture-guardrails'}],
  sidebar_cx_bok: [{type: 'autogenerated', dirName: 'cx-bok'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
