import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  sidebar_standards: [{type: 'autogenerated', dirName: 'standards'}],
  sidebar_non_functional: [
    'rulebooks/overview',
    {
      type: 'category',
      label: 'Conformity Assessment Framework',
      collapsed: true,
      items: [
        'rulebooks/CX-NFR-CAF/introduction-and-framework',
        'rulebooks/CX-NFR-CAF/cab-conformity-assessment-body',
        'rulebooks/CX-NFR-CAF/cx-standards-roles-and-certification-objects',
        'rulebooks/CX-NFR-CAF/modular-system-and-cross-cutting-requirements',
        'rulebooks/CX-NFR-CAF/certification-catalog',
        'rulebooks/CX-NFR-CAF/test-procedures',
        'rulebooks/CX-NFR-CAF/certification-process-certificate-and-updates',
        'rulebooks/CX-NFR-CAF/appendix',
      ],
    },
    {
      type: 'category',
      label: 'Identity Proofing',
      collapsed: true,
      items: [
        'rulebooks/CX-NFR-IdP/CX-NFR-IdP',
        'rulebooks/CX-NFR-IdP/Changelog'
      ],
    },
    'rulebooks/CX-NFR-PCF/CX-NFR-PCF',
    'rulebooks/CX-NFR-VF/CX-NFR-VF',
  ],
  sidebar_op_model: [{type: 'autogenerated', dirName: 'operating-model'}],
  sidebar_regulatory_framework: [{type: 'autogenerated', dirName: 'regulatory-framework'}],
  sidebar_working_model: [{type: 'autogenerated', dirName: 'working-model'}],
  sidebar_architecture_guardrails: [{type: 'autogenerated', dirName: 'architecture-guardrails'}],
  sidebar_cx_bok: [{type: 'autogenerated', dirName: 'cx-bok'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
