@startuml identifier-type

package "Identifier Type and References" {

  class LegalEntityIdentifier {
    Value
    IssuingBody
  }

  class AddressIdentifier{
    Value
  }

  entity IdentifierType {
    TechnicalKey
    Name
    ' Abbreviation
    ' TransliteratedName
    ' TransliteratedAbbreviation
  }

  enum BusinessPartnerType {
    LegalEntity
    Address
  }

  ' not standardized yet
  ' class IdentifierTypeDetail {
  '   Mandatory
  ' }

  ' not standardized yet
  ' enum Country {
  '   DE
  '   FR
  '   US
  '   ...
  ' }

  IdentifierType "*" -d-o "1" BusinessPartnerType : BusinessPartnerType

  LegalEntityIdentifier "*" -d-o "1" IdentifierType : Type
  AddressIdentifier "*" -d-o "1" IdentifierType : Type

  ' not standardized yet
  ' IdentifierType "1" *-d-> "*" IdentifierTypeDetail : Details
  ' IdentifierTypeDetail "*" -r-o "1" Country : Country
}

hide methods
@enduml