@startuml identifier-type

skinparam dpi 50

package "Identifier Type and References" {

  entity IdentifierType {
    TechnicalKey
    Name
    Abbreviation
    TransliteratedName
    TransliteratedAbbreviation
    Format
  }

  enum BusinessPartnerType {
    LegalEntity
    Address
  }

  enum IdentifierTypeCategory {
    VAT
    TIN
    NBR
    IBR
    OTH
  }

  class IdentifierTypeDetail {
    Mandatory
  }

  enum Country {
    DE
    FR
    US
    ...
  }

  IdentifierType "*" -d-o "1" BusinessPartnerType : BusinessPartnerType
  IdentifierType "*" -o "*" IdentifierTypeCategory : IdentifierTypeCategory

  IdentifierType "1" *-d-> "*" IdentifierTypeDetail : Details
  IdentifierTypeDetail "*" -r-o "1" Country : Country
}

hide methods
@enduml