@startuml Figure_4
autonumber
skinparam sequenceMessageAlign center

box "Data Provider"
participant "Business\nApplication" as app_prov
end box

box "Data Consumer"
participant "Business\nApplication" as app_cons
end box

app_prov ->  app_cons: Send "Request for Quotation"
note right: Request for Quotation Endpoint
return Created

@enduml