@startuml example-for-bpn

package "Example 'Porsche AG' with Its Legal Entity, One of Its Sites and Three Addresses" {
  object LegalEntity {
    LegalName = "Dr. Ing. h.c. F. Porsche Aktiengesellschaft"
    ShortName = "Porsche AG"
    BPNL = "BPNL000000001F61"
  }

  object Address1 {
    Name = ""
    BPNA = "BPNA000000001K6B"
    Country = "DE"
    City = "Stuttgart"
    PostalCode = "70435"
    Street = "Porscheplatz"
    HouseNumber = "1"
  }

  object Address2 {
    Name = "Pforte (Lieferanten)"
    BPNA = "BPNA000000001J39"
    Country = "DE"
    City = "Stuttgart"
    PostalCode = "70435"
    Street = "Schwieberdinger Str."
    HouseNumber = "130"
  }

  object Address3 {
    Name = "Hauptpforte"
    BPNA = "BPNA000000001L5M"
    Country = "DE"
    City = "Stuttgart"
    PostalCode = "70435"
    Street = "Porschestraße"
    HouseNumber = "42
  }

  object Site1 {
    Name = "Porsche Zuffenhausen, Werk 2"
    BPNS = "BPNS00000003CRHK"
  }

  ' object BusinessPartner {
  '   AddressType = "AdditionalAddress"
  '   NameParts = [
  '     "Dr. Ing. h.c. F. Porsche", 
  '     "Aktiengesellschaft", 
  '     "Porsche Zuffenhausen,", 
  '     "Werk 2, Pforte (Lieferanten)"]
  '   Country = "DE"
  '   City = "Stuttgart"
  '   PostalCode = "70435"
  '   Street = "Schwieberdinger Str."
  '   HouseNumber = "130"
  ' }

  ' BusinessPartner -r-> LegalEntity : BPNL
  ' BusinessPartner -r-> Site1 : BPNS
  ' BusinessPartner -r-> Address2 : BPNA
  LegalEntity .d.> Address1 : LegalAddress
  Site1 .d.> Address3 : SiteMainAddress
  Address1 -u-> LegalEntity : BPNL
  Address2 -u-> Site1 : BPNS
  Address2 -u-> LegalEntity : BPNL
  Address3 -u-> Site1 : BPNS
  Address3 -u-> LegalEntity : BPNL
  Site1 -u-> LegalEntity : BPNL
}

@enduml

